---
title: "FHWA fuel data"
author: ""
date: "7/20/16"
output: html_document
---


## GHG differences  
  
> FUEL SALES: 2005 to 2012 shows ~~7%~~ __5.5%__ drop after 2012 diesel corrected (6% increase)  


> MOVES: 2005 to 2012 shows ~~1%~~ 3% drop after VMT update (1.5% VMT increase for 2005 - 2007)  


> MOVES: 2005 to __2014__ shows ~~3.5%~~ __5%__ drop


## Why aren't MOVES emissions decreasing more quickly?

Big changes  

1.  People are buying bigger cars.
    - Increase of 7-8% in heavier vehicles: SUVs / Trucks / Vans.    
1.  The fleet got older.  
    - Average age of vehicles increased during recession.  
    - Rate of new car purchases still behind 2005 rate.  


Small changes  

1.  E0 premium sales have increased 12%.  
1.  E85 use dropped off after 2008.  
1.  Small increase in diesel use.  
1.  Travel model shows more vehicles traveling over 70 mph on rural highways.  
    - > 67% in 2005  
    - > 75% in 2014  


## Why don't fuel sales show a smaller decrease?

1.  The inventory under reported diesel sales in 2012 by 60 million gallons (~6%).
2.  In 2005 the FHWA apportioned the largest percentage of fuel sales to on-road vehicles (~1% more), and a smaller portion to non-road.


FHWA fuel reference   

  - [Diesel 2005 to 2013 - Public Data Explorer](https://www.google.com/publicdata/explore?ds=gb66jodhlsaab_#!ctype=l&strail=false&bcs=d&nselm=h&met_y=Special_Fuel&scale_y=lin&ind_y=false&rdim=state&idim=state:MN&ifdim=state&tstart=1118898000000&tend=1371358800000&hl=en_US&dl=en_US&ind=false)   
  - [2005 - 2014 - FHWA Report MF21](https://www.fhwa.dot.gov/policyinformation/statistics/2014/mf21.cfm)  


```{r echo=F, message=F, warning=F}
library(dplyr)

diesel <- data_frame(Year = 2005:2014, 
                     Fuel = "Diesel", 
                     gallons = 
c(665699000,
675627000,
677757000,
668423000,
598711000,
625992000,
657755000,
690567500,
662062000,
673561000))

on_gas <- data_frame(Year = 2005:2014, 
                     Fuel = "Gas On-road", 
                     gallons = 
c(2596846E+03,
2504236E+03,
2516616E+03,
2505583E+03,
2434507E+03,
2452821E+03,
2360340E+03,
2429561E+03,
2389435E+03,
2409882E+03))

off_gas <- data_frame(Year = 2005:2014, 
                      Fuel = "Gas Off-road", 
                      gallons = 
c(110626E+03,
160519E+03,
148333E+03,
118876E+03,
117468E+03,
130370E+03,
129044E+03,
123844E+03,
130410E+03,
124884E+03))

#off_gas <- mutate(off_gas, Change = c(0, diff(gallons)))
#filter(fuel, Year == Year+1, Fuel == Fuel)$gallons

fuel <- rbind(on_gas, off_gas, diesel)

group_by(fuel, Year) %>% summarize(Gallons = sum(gallons))

fuel <- group_by(fuel, Fuel) %>% mutate(Change = c(0, diff(gallons)))

setwd("C:/Users/dkvale/Desktop")

write.csv(fuel, "FHWA_fuel.csv", row.names=F)

```


Fossil CO2-eq tons

|    Year  |    CO2     |  
|----------|------------|  
|   2005   | 32,256,787 |  
|   2006   | 32,255,962 |  
|   2007   | 32,716,718 |  
|   2008   | 32,393,603 |  
|   2009   | 31,407,156 |  
|   2010   | 31,447,466 |  
|   2011   | 31,719,670 |  
|   2012   | 31,885,081 |  
|   2013   | 31,477,224 |  
|   2014   | 31,081,875 |  

##
